### ISSUE TITLE
Integration test src/intTest/java/com/surrealdb/driver/SurrealDriverSpecialOperationsTest.java failing

### ISSUE THREAD

**Issue by eharrow** [surrealdb/surrealdb.java#35]
Pulled the latest version and have just run the integration tests.  One fails in src/intTest/java/com/surrealdb/driver/SurrealDriverSpecialOperationsTest.java - testSignUp()

Logs have the following:

```
2023-04-26 15:45:34.650 ERROR [ctReadThread-28] c.s.c.SurrealWebSocketConnection         : Received RPC error: id=1 code=-32000 message=There was a problem with authentication

com.surrealdb.connection.exception.SurrealAuthenticationException
	at app//com.surrealdb.connection.ErrorToExceptionMapper.map(ErrorToExceptionMapper.java:22)
	at app//com.surrealdb.connection.SurrealWebSocketConnection.onMessage(SurrealWebSocketConnection.java:148)
	at app//org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:636)
```

There is no assertion in the test anyway therefore this is not a test.  Can I suggest starting with a unit test first before moving onto the integration test.  The unit test should mock the behaviour of the `connection.rpc(… )` to verify that the arguments sent to it are as expected.

**Comment by eharrow** [comment]
The root cause seems to be an auth error with the test's namespace and scope from what I can tell.

**Comment by phughk** [comment]
Resolved! 🎉
