### ISSUE TITLE
Bug: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by 047massi** [surrealdb/surrealdb.java#90]
### Describe the bug

I encountered a java.lang.UnsatisfiedLinkError when calling the queryBind method.

### Steps to reproduce

`surreal.queryBind("SELECT * FROM table WHERE id = $id", paramsMap);`

### Expected behaviour

The `queryBind` method should successfully execute a parameterized query on the database without throwing any errors. It should bind the specified parameters to the query and return the expected result set or a successful response

### SurrealDB version

surreal 2.0.4

### Contact Details

m46955611@gmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by odwrotnie** [comment]
Same problem here :(

**Comment by i1Fury** [comment]
Same problem. Any plans on continuing work on this repository?

`response = this.driver.queryBind(
                    "UPSERT $what SET $object;",
                    Map.of("what", what, "object", object)
            );`

`Caused by: java.lang.UnsatisfiedLinkError: 'long com.surrealdb.Surreal.queryBind(long, java.lang.String, java.util.Map)'`

**Comment by masterofdaemon** [comment]
something similar :   `No implementation found for boolean com.surrealdb.Entry.deleteInstance(long) (tried Java_com_surrealdb_Entry_deleteInstance and Java_com_surrealdb_Entry_deleteInstance__J) - is the library loaded, e.g. System.loadLibrary?
2025-10-04 01:02:40.854 14717-14725 System                  com.example.kmp                      E  Uncaught exception thrown by finalizer
2025-10-04 01:02:40.854 14717-14725 System                  com.example.kmp                      E  java.lang.UnsatisfiedLinkError: No implementation found for boolean com.surrealdb.Entry.deleteInstance(long) (tried Java_com_surrealdb_Entry_deleteInstance and Java_com_surrealdb_Entry_deleteInstance__J) - is the library loaded, e.g. System.loadLibrary?
                                                                                                    	at com.surrealdb.Entry.deleteInstance(Native Method)
                                                                                                    	at com.surrealdb.Native.deleteInstance(Native.java:25)
                                                                                                    	at com.surrealdb.Native.finalize(Native.java:58)
                                                                                                    	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:339)
                                                                                                    	at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:324)
                                                                                                    	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:300)
                                                                                                    	at java.lang.Daemons$Daemon.run(Daemons.java:145)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2025-10-04 01:02:40.854 14717-14725 com.example.kmp         com.example.kmp                      E  No implementation found for boolean com.surrealdb.Entry.deleteInstance(long) (tried Java_com_surrealdb_Entry_deleteInstance and Java_com_surrealdb_Entry_deleteInstance__J) - is the library loaded, e.g. System.loadLibrary?
2025-10-04 01:02:40.854 14717-14725 System                  com.example.kmp                      E  Uncaught exception thrown by finalizer`

**Comment by emmanuel-keller** [comment]
Thanks all for the reports. This issue dates from `1.0.0-beta.1`. The driver has since shipped `2.0.0` (stable) and `2.0.1`, and the parameter-binding path has been rewritten in #148 — `Surreal.queryBind(...)` now delegates to a new `Surreal.query(String, Map<String, ?>)` overload with full JNI coverage and regression tests.

The `UnsatisfiedLinkError` itself indicates the native library wasn't loaded for the running platform. The driver ships native binaries for Linux x86_64/aarch64, Windows x86_64, macOS x86_64/aarch64, and Android x86_64/aarch64; running on any other target — or against an old jar that predates a binary for your platform — will produce this error.

Closing as resolved by the rewrite. If you can still reproduce against `2.0.1` on a supported platform, please open a fresh issue with the OS/architecture, JDK version, and a minimal repro.
