### ISSUE TITLE
Bug: ValueBuilder cannot access a member of class ...Person with modifiers ""

### ISSUE THREAD

**Issue by odwrotnie** [surrealdb/surrealdb.java#91]
### Describe the bug

I am running the example from README, and this is the result:

```
com.surrealdb.SurrealException: Unable to convert object
 at com.surrealdb.ValueBuilder.convert([ValueBuilder.java:93](vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at com.surrealdb.Surreal.contents2longs([Surreal.java:320](vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at com.surrealdb.Surreal.create([Surreal.java:154](vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at com.surrealdb.Surreal.create([Surreal.java:161](vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at CreateItemTest.testHelloWorld([CreateItemTest.java:24](vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at java.base/java.util.ArrayList.forEach(Unknown Source)
 at java.base/java.util.ArrayList.forEach(Unknown Source)
Caused by: java.lang.IllegalAccessException: class com.surrealdb.ValueBuilder cannot access a member of class CreateItemTest$Person with modifiers ""

 at java.base/java.lang.reflect.AccessibleObject.checkAccess(Unknown Source)
 at java.base/java.lang.reflect.Field.checkAccess(Unknown Source)
 at java.base/java.lang.reflect.Field.get(Unknown Source)
 at com.surrealdb.ValueBuilder.convertObject([ValueBuilder.java:79](vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at com.surrealdb.ValueBuilder.convert([ValueBuilder.java:91](vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 ... 74 more
```

### Steps to reproduce

Run the database:

```docker
  surrealdb:
    image: surrealdb/surrealdb:latest
    hostname: instap-es-surrealdb
    ports:
      - "8000:8000"
    command: [ "start", "--bind", "0.0.0.0:8000", "--unauthenticated", "rocksdb://data/x.db" ]
    user: root
    restart: unless-stopped
    volumes:
      - surreal_data:/data
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "1G"
```

Run the example:

```java
import java.util.Iterator;
import java.util.List;
import org.junit.jupiter.api.Test;
import com.surrealdb.Surreal;

public class CreateItemTest {
    
    @Test
    void test() {
        
        try (final Surreal driver = new Surreal()) {

            driver.connect("ws://localhost:8000");
            driver.useNs("x").useDb("x");
            
            // Create a person
            Person person = new Person("Founder & CEO", "Tobie", "Morgan Hitchcock", true);
            // Insert a record
            List<Person> tobie = driver.create(Person.class, "person", person);
            // Read records
            Iterator<Person> people = driver.select(Person.class, "person");
            // Print them out
            System.out.println("Tobie = " + tobie);
            System.out.println("people = " + people.next());
        }
    }

    static class Person {
        String id;
        String title;
        String firstName;
        String lastName;
        boolean marketing;

        //  A default constructor is required
        public Person() {
        }

        public Person(String title, String firstName, String lastName, boolean marketing) {
            this.title = title;
            this.firstName = firstName;
            this.lastName = lastName;
            this.marketing = marketing;
        }

        @Override
        public String toString() {
            return "Person{" +
                    "id='" + id + '\'' +
                    ", title='" + title + '\'' +
                    ", firstName='" + firstName + '\'' +
                    ", lastName='" + lastName + '\'' +
                    ", marketing=" + marketing +
                    '}';
        }
    }
}
```

### Expected behaviour

I was expecting the Person in database

### SurrealDB version

surrealdb/surrealdb:latest

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by odwrotnie** [comment]
I think I have found the solution - `id` should be typed with `RecordId`.
