### ISSUE TITLE
Bug: UnsatisfiedLinkError for newThingStringId

### ISSUE THREAD

**Issue by odwrotnie** [surrealdb/surrealdb.java#92]
### Describe the bug

During `new RecordId(SurrealItem.THING, itemId)` you get `java.lang.UnsatisfiedLinkError: 'long com.surrealdb.RecordId.newThingStringId(java.lang.String, java.lang.String)'`

```
java.util.concurrent.CompletionException: java.lang.UnsatisfiedLinkError: 'long com.surrealdb.RecordId.newThingStringId(java.lang.String, java.lang.String)'
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.UnsatisfiedLinkError: 'long com.surrealdb.RecordId.newThingStringId(java.lang.String, java.lang.String)'
        at com.surrealdb.RecordId.newThingStringId(Native Method)
        at com.surrealdb.RecordId.<init>(RecordId.java:15)
        at service.SurrealSetValueService.process(SurrealSetValueService.java:53)
        at consumer.SurrealItemConsumer.on(SurrealItemConsumer.java:54)
        at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169)
        at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119)
        at org.springframework.kafka.listener.adapter.HandlerAdapter.invoke(HandlerAdapter.java:56)
        at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:375)
        at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter.onMessage(RecordMessagingMessageListenerAdapter.java:92)
        at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter.onMessage(RecordMessagingMessageListenerAdapter.java:53)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:2873)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeOnMessage(KafkaMessageListenerContainer.java:2854)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.lambda$doInvokeRecordListener$57(KafkaMessageListenerContainer.java:2772)
        at io.micrometer.observation.Observation.lambda$observe$4(Observation.java:544)
        at io.micrometer.observation.Observation.observeWithContext(Observation.java:603)
        at io.micrometer.observation.Observation.observe(Observation.java:544)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:2770)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:2622)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:2508)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:2150)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeIfHaveRecords(KafkaMessageListenerContainer.java:1505)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1469)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1344)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
```

### Steps to reproduce

`new RecordId(SurrealItem.THING, itemId)`

### Expected behaviour

It should create the RecordId without 

### SurrealDB version

SurrealDB: v2, library: 0.2.0

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by odwrotnie** [comment]
Fixed here: https://github.com/surrealdb/surrealdb.java/pull/93

**Comment by emmanuel-keller** [comment]
Thanks @odwrotnie great fix & contribution!
